server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: true
reflectoring:
  trace: true
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  messages:
    basename: lang/res
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false